name: summarization
description: Summarize a text
pipeline:
  task: summarization
  model: t5-base
  tokenizer: t5-base
  framework: tf
input:
  data:
    text:
      type: string
      required: true
      description: The question to answer
    params:
      type: object
      required: false
      description: Additional parameters
      properties:
        max_length:
          type: integer
          required: false
          default: 30
          description: The maximum length of the summary
        min_length:
          type: integer
          required: false
          default: 5
          description: The minimum length of the summary
        do_sample:
          type: boolean
          required: false
          default: false
          description: Whether or not to use sampling ; use greedy decoding otherwise.
        early_stopping:
          type: boolean
          required: false
          default: true
          description: Whether to stop the beam search when at least num_beams sentences are finished per batch or not.
        num_beams:
          type: integer
          required: false
          default: 1
          description: Number of beams for beam search. 1 means no beam search.
        temperature:
          type: float
          required: false
          default: 1.0
          description: The value used to module the next token probabilities.
        top_k:
          type: integer
          required: false
          default: 50
          description: The number of highest probability vocabulary tokens to keep for top-k-filtering.
        top_p:
          type: float
          required: false
          default: 1.0
          description: If set to float < 1, only the most probable tokens with probabilities that add up to top_p or higher are kept for generation.
        repetition_penalty:
          type: float
          required: false
          default: 1.0
          description: The parameter for repetition penalty. 1.0 means no penalty. See this paper for more details.
        length_penalty:
          type: float
          required: false
          default: 1.0
          description: Exponential penalty to the length. 1.0 means no penalty.
        no_repeat_ngram_size:
          type: integer
          required: false
          default: 0
          description: If set to int > 0, all ngrams of that size can only occur once.
        num_return_sequences:
          type: integer
          required: false
          default: 1
          description: The number of independently computed returned sequences for each element in the batch.
  example: {text: "An apple a day, keeps the doctor away", params: {min_length=5, max_length=20}}
output:
  data:
    type: array
    description: List of results
    items:
      summary_text:
        type: string
        description: Generated text
  example: [{'summary_text': "This is just a fallback response!"}]