export const testData = [
  {
    id: "11111",
    firstname: "Paul",
    lastname: "Watermelon",
    username: "",
    email: "yellow@hello.com",
    roles: "Student*in",
    key: "-1",
    status: "new",
  },
  {
    id: "78511",
    firstname: "Pineapple",
    lastname: "Salmon",
    username: "",
    email: "red@hello.com",
    roles: "Student*in",
    key: "-1",
    status: "new",
  },
  {
    id: "78511",
    firstname: "Frank",
    lastname: "Cheng",
    username: "",
    email: "blue@hello.com",
    roles: "Student*in",
    key: "-1",
    status: "new",
  },
  {
    id: "78511",
    firstname: "Test",
    lastname: "User",
    username: "",
    email: "purple@hello.com",
    roles: "Student*in",
    key: "-1",
    status: "new",
  },
  {
    id: "785122",
    firstname: "Test",
    lastname: "User",
    username: "",
    email: "hello@hello.com",
    roles: "Student*in",
    key: "-1",
    status: "duplicate",
  },
  {
    id: "232",
    firstname: "Peter",
    lastname: "Pan",
    username: "",
    email: "hello@hello.com",
    roles: "Student*in",
    key: "-1",
    status: "duplicate",
  },
];
