version: "3"
services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1s
  content_server:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - ${PUBLISHED_PORT}:${CONTENT_SERVER_PORT}
    env_file:
      - .env.dev
  nlp:
    build:
      context: .
      dockerfile: nlp/Dockerfile
      args:
        - env=.env.build
    depends_on:
      - rabbitmq
      - celery-worker
      - grobid
      - redis
    command: python3 app.py
    ports:
      - ${NLP_PORT}:${NLP_PORT}
    env_file:
      - .env.dev
  grobid:
    image: lfoppiano/grobid:0.7.0
    ports:
      - ${GROBID_PORT}:8070
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - ${RABBITMQ_PORT}:5672
      - 15673:15672
  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6379
  celery-worker:
    build:
      context: .
      dockerfile: nlp/Dockerfile
    environment:
      - C_FORCE_ROOT=true
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - .env.dev
    command: celery -A app.celery worker -l INFO -E
  flower:
    image: mher/flower
    depends_on:
      - rabbitmq
      - celery-worker
    command: celery flower --broker=amqp://${RABBITMQ_HOST}:${RABBITMQ_PORT} --port=8888
    ports:
    - ${FLOWER_PORT}:8888