version: "3"
services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1s
  server:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - ${PUBLISHED_PORT}:${CONTENT_SERVER_PORT}
    env_file:
      - .env